name: swiper_view_pro
description: A Flutter swiper/carousel with multiple layouts, infinite loop, and configurable 3D effects. Compatible with Android and iOS.
version: 0.1.0
homepage: https://github.com/whevether/flutter_swiper_view

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
